# run `docker compose up` in CLI, to run, and then click on the localhost link
# after running, run `docker compose down` to stop the container

services:
  api:
    build: .
    container_name: forwardair-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
