# run `docker compose up` in CLI, to run, but don't click on the localhost link
# instead, open your browser and go to http://localhost:8501/docs to see interface
# after running, run `docker compose down` to stop the container

services:
  streamlit:
    build: .
    container_name: forwardair-streamlit
    ports:
      - "8501:8501"
    volumes:
      # Persist FAISS index between runs (optional, but useful)
      - ./faiss_index:/app/faiss_index
    restart: unless-stopped
